### ISSUE TITLE
feat: support multi library

### ISSUE THREAD

**Issue by huang12zheng** [trane-project/trane-cli#14]
* motion
We use trane to go to the command line,
And, there's command `open [library]`, which is very flexible.
But, I have an idea:
Perhaps we can open multiple libraries in the same workspace
Semantically add the course from each library to the workspace

**Comment by huang12zheng** [comment]
Maybe I need to explain a little bit about workspaces, 
the idea came from
```
let history_path = std::path::Path::new(".trane_history");
```
> By the way, I was surprised at first why it wasn't generated in HOME,
> But I found it cool to use workspaces

**Comment by martinmr** [comment]
I didn't add it to HOME because it wasn't clear what HOME would be in Windows for example.

I am not really understanding what this means. What exactly is a workspace in this case? Do you want to be able to open multiple libraries and combine them into a single one so that you can practice questions from all of them?

**Comment by huang12zheng** [comment]
> I didn't add it to HOME because it wasn't clear what HOME would be in Windows for example.

You don't have to worry about it. It's noise


> Do you want to be able to open multiple libraries and combine them into a single one so that you can practice questions from all of them?

You said it. That's what I think

**Comment by martinmr** [comment]
Not sure if you know this, but you can already easily combine courses from multiple sources under a single Trane library. Let's say for example, you are using `trane-music` but you also have courses of your own. If you store them under the following directory structure:

```
root/
    trane-music/
    my-music-courses/
```

and then call `open root/` in trane-cli, Trane will create a `.trane` directory under `root` and open all the courses in `trane-music` and `my-music-courses`, effectively doing something like you asked. Is this good enough for your use case?

But if you want to keep each Trane library separate and have the option to open multiple ones at once, it's still possible. What I am not sure is why you would want to do that instead of simply combining all the courses under a common folder.
